version: '3'

services:
  nginx:
    image: lunacircle4/nginx:floweryroad-backend # nginx 서비스에서 사용할 도커 이미지
    ports:
      - "80:80"
    volumes:
      - ../../.credentials/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../../../static:/app/static  
      - ../../../media:/app/media
    depends_on: # 서비스 간의 종속성 표현
      - web
    
  db:
    env_file: 
      - ../../.credential/db.env
    image: postgres
    volumes:
      - ../../../db_volume:/var/lib/postgresql/data
  
  web:
    env_file: 
      - ../../.credential/was.env
    image: lunacircle4/floweryroad-backend

    volumes:
      - ../../../static:/web/static  
      - ../../../media:/web/media
    
    depends_on: # 서비스 간의 종속성 표현
      - db

    command: 
      - /bin/bash
      - -c
      - |
        supervisord



  
