apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-db
  namespace: floweryroad
spec:
  selector:
    matchLabels:
      app: production-db
  template:
    metadata:
      labels:
        app: production-db
    spec:
      containers:
      - name: db
        image: postgres:12.2-alpine
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume
        envFrom:
        - secretRef:
            name: production-db
      volumes:
      - name: db-volume
        hostPath:
          # directory location on host and most create folder before apply
          path: /volumes/floweryroad-db-volume
          # this field is optional
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: production-db
  namespace: floweryroad
spec:
  ports:
    - name: db-port
      port: 5432
      targetPort: 5432
  selector:
    app: production-db
  type: ClusterIP
