version: "3"

services:
  database:
    env_file: 
      - envs/database/development.env
    image: postgres:12.2-alpine
    container_name: database.development.floweryroad-backend
    volumes:
      - database.development.floweryroad:/var/lib/postgresql/data

  logic:
    env_file:
      - envs/logic/development.env
    container_name: logic.development.floweryroad-backend
    build:
      context: ./
      dockerfile: docker/development/Dockerfile
    volumes:
      - "./:/floweryroad"
    ports:
      - "8000:8000"

volumes:
  database.development.floweryroad:
    external: true
