# Generated by Django 2.2.2 on 2019-08-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('season', models.IntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Fall'), (4, 'Winter')], default=1)),
                ('colors', models.ManyToManyField(related_name='flowers', to='core.Color')),
                ('languages', models.ManyToManyField(related_name='flowers', to='core.Language')),
                ('purposes', models.ManyToManyField(related_name='flowers', to='core.Purpose')),
            ],
        ),
    ]
