version: '3'

services:
  db:
    image: postgres
    volumes:
      - /app/floweryroad-backend/docker/db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  web:
    env_file: credential.env
    image: floweryroad-backend:1.0.0

    ports:
      - "8000:8000"
    
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_USER}
      - DB_USER=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}

    command: 
      - /bin/bash
      - -c
      - |
        python /app/floweryroad-backend/manage.py migrate
        sudo systemctl enable uwsgi
        sudo systemctl daemon-reload
        sudo systemctl restart uwsgi nginx
  
