# Generated by Django 2.2.2 on 2019-08-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flower_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='')),
                ('flower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Flower')),
            ],
        ),
    ]
