version: '3'

services:
  db:
    image: postgres
    env_file: 
      - /Users/kimdongwon/Documents/WebProgramming/Projects/Floweryroad/floweryroad-backend/.credential/dev/db_credential.env
    volumes:
      - ../../db_volume:/var/lib/postgresql/data

  web:
    image: lunacircle4/floweryroad-backend:develop
    env_file: 
      - /Users/kimdongwon/Documents/WebProgramming/Projects/Floweryroad/floweryroad-backend/.credential/dev/credential.env
    volumes:
      - ../../web:/app/web
    ports:
      - "8000:8000"
    depends_on: 
      - db
    command: 
      - /bin/zsh
      - -c
      - |
        source /root/.pyenv/versions/floweryroad/bin/activate
        python /app/web/manage.py migrate
        python /app/web/manage.py runserver 0.0.0.0:8000
  
