# Generated by Django 2.2.4 on 2019-08-09 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('floweryroad-auth', '0002_auto_20190806_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deta_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
